<?php

########################################################################
# Extension Manager/Repository config file for ext: "slub_forms"
#
# Auto generated by Extension Builder 2013-08-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SLUB Forms',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Alexander Bigga',
	'author_email' => 'alexander.bigga@slub-dresden.de',
	'author_company' => 'SLUB Dresden',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'uploads/tx_slubforms/',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.4.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-7.6.99',
			'fluid' => '6.2.0-7.6.99',
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
